# Generated by Django 4.2.13 on 2024-05-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=50, verbose_name='Nome do cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email do cliente')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone_cliente', models.CharField(max_length=255, verbose_name='Telefone do cliente')),
                ('rua_endereco', models.CharField(max_length=50)),
                ('numero_endereco', models.IntegerField()),
                ('cidade_endereco', models.CharField(max_length=255)),
                ('estado_edereco', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=5, unique=True, verbose_name='Nome do produto')),
                ('quantidade_produto', models.IntegerField(verbose_name='Quantidade do produto')),
                ('precocompra_produto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço de compra do produto')),
                ('precovenda_produto', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço de venda do produto')),
            ],
        ),
    ]
