# Generated by Django 4.2.13 on 2024-05-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='id_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(max_length=255, verbose_name='Nome do cliente'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome do produto'),
        ),
    ]
