# Generated by Django 4.2.13 on 2024-05-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_produto_id_produto_produto_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cidade_endereco',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='estado_edereco',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='numero_endereco',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='rua_endereco',
            new_name='rua',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default=0, max_length=8, verbose_name='CEP:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, help_text='Informe apenas números', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_cliente',
            field=models.EmailField(max_length=254, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(max_length=255, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='precocompra_produto',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço de compra:'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='precovenda_produto',
            field=models.DecimalField(decimal_places=5, max_digits=6, verbose_name='Preço de venda:'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_produto',
            field=models.IntegerField(verbose_name='Quantidade:'),
        ),
    ]
