# Generated by Django 4.2.13 on 2024-05-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_rename_cidade_endereco_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='precocompra_produto',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço de compra:'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='precovenda_produto',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço de venda:'),
        ),
    ]
