# Generated by Django 4.2.13 on 2024-05-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(default='cliente', max_length=50),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(default='produto', max_length=50),
        ),
    ]
