# Generated by Django 4.2.13 on 2024-05-30 18:49

import cadastros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_cliente_tipo_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(help_text='Informe apenas números', max_length=14, unique=True, validators=[cadastros.models.validate_cpf], verbose_name='CPF'),
        ),
    ]
